### PR TITLE
adding munge to ldms-static-test list

### PR DESCRIPTION
**Pull request by Snell1224**
Adding munge to plugin list for ldms-run-static-test.

### CODE REVIEW

**Comment by baallan** [comment]
Isn't there a .in file involved here? We should be using $pkglibdir and not having your home directory appear in the repo.

(admittedly, I need to fix such things in my tests occasionally)-- in fact I have one in #458 still pending.

**Comment by Snell1224** [comment]
Ah, yes you're right. That's not supposed to be there. I got confused on which one I was one and accidently pushed to the wrong branch. Thanks for letting me know!

**Comment by baallan** [comment]
@Snell1224 Is there a revision to this or a replacement PR? or is it ready to go?

**Comment by Snell1224** [comment]
@baallan yes it is ready to go. Already revised it and fixed the issue.

**Pull request merged**
