### PR TITLE
Remove a generated file, config/tap-driver.sh

### PR DESCRIPTION
**Pull request by nichamon**
The file is generated by autoconf per macro
AC_REQUIRE_AUX_FILE([tap-driver.sh]) in configure.ac.

### CODE REVIEW

**Comment by nichamon** [comment]
@baallan @Snell1224 `config/tap-driver.sh` is generated by autoconf. Please do not add any generated files to the tree. 

The problem is that different versions of the tool that generates the file (in this case, autoconf) may generate slightly different content. Without this patch on Ubuntu 18.04, after calling `./autogen.sh` the file will be changed.

What I tested is:

From a clean tree, I removed `config/tap-driver.sh`. After I ran `./autogen.sh`, `tap-driver.sh` exists in the `config` directory.

**Comment by baallan** [comment]
@Snell1224 I cloned and tried Mon's code on my centos 7. It ends up with the same tap-driver.sh, so her pull request seems to be fine.

I notice (./configure --enable-ldms-test --disable-python --prefix=/tmp/pc && make installcheck) that practically everything tested is coming up XFAIL (e.g. meminfo) which I think is unexpected. 
Also, it looks like maybe some of the recent configure.ac papi-related changes from Chris may require adjustments to the test scripting.
Below is the relevant output from make installcheck. 

```
Making installcheck in test
make[3]: Entering directory `/tmp/novis/ldms/src/test'
./ldms-run-static-tests.test
/tmp/pc/lib/ovis-ldms/ldms-static-test-list.sh: line 6: @ENABLE_PAPI_SAMPLER_TRUE@: command not found
/tmp/pc/lib/ovis-ldms/ldms-static-test-list.sh: line 7: @ENABLE_SYSPAPI_SAMPLER_TRUE@: command not found
/tmp/pc/lib/ovis-ldms/ldms-static-test-list.sh: line 14: @ENABLE_RAPL_TRUE@: command not found
1..21
FAIL: cannot read test input meminfo
meminfo
not ok 1 - XFAIL: meminfo # TODO - If test is not an expected failure, please remove meminfo from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.meminfo.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.meminfo.log: No such file or directory
FAIL: cannot read test input generic_sampler
generic_sampler
not ok 2 - XFAIL: generic_sampler # TODO - If test is not an expected failure, please remove generic_sampler from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.generic_sampler.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.generic_sampler.log: No such file or directory
FAIL: cannot read test input tsampler
tsampler
not ok 3 - XFAIL: tsampler # TODO - If test is not an expected failure, please remove tsampler from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.tsampler.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.tsampler.log: No such file or directory
FAIL: cannot read test input hfclock
hfclock
not ok 4 - XFAIL: hfclock # TODO - If test is not an expected failure, please remove hfclock from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.hfclock.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.hfclock.log: No such file or directory
FAIL: cannot read test input dstat
dstat
not ok 5 - XFAIL: dstat # TODO - If test is not an expected failure, please remove dstat from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.dstat.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.dstat.log: No such file or directory
FAIL: cannot read test input loadavg
loadavg
not ok 6 - XFAIL: loadavg # TODO - If test is not an expected failure, please remove loadavg from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.loadavg.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.loadavg.log: No such file or directory
FAIL: cannot read test input procinterrupts
procinterrupts
not ok 7 - XFAIL: procinterrupts # TODO - If test is not an expected failure, please remove procinterrupts from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.procinterrupts.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.procinterrupts.log: No such file or directory
FAIL: cannot read test input procstat
procstat
not ok 8 - XFAIL: procstat # TODO - If test is not an expected failure, please remove procstat from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.procstat.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.procstat.log: No such file or directory
FAIL: cannot read test input procnetdev
procnetdev
not ok 9 - XFAIL: procnetdev # TODO - If test is not an expected failure, please remove procnetdev from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.procnetdev.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.procnetdev.log: No such file or directory
FAIL: cannot read test input vmstat
vmstat
not ok 10 - XFAIL: vmstat # TODO - If test is not an expected failure, please remove vmstat from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.vmstat.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.vmstat.log: No such file or directory
FAIL: cannot read test input clock
clock
not ok 11 - XFAIL: clock # TODO - If test is not an expected failure, please remove clock from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.clock.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.clock.log: No such file or directory
FAIL: cannot read test input variable
variable
not ok 12 - XFAIL: variable # TODO - If test is not an expected failure, please remove variable from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.variable.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.variable.log: No such file or directory
FAIL: cannot read test input array_example
array_example
not ok 13 - XFAIL: array_example # TODO - If test is not an expected failure, please remove array_example from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.array_example.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.array_example.log: No such file or directory
FAIL: cannot read test input synthetic
synthetic
not ok 14 - XFAIL: synthetic # TODO - If test is not an expected failure, please remove synthetic from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.synthetic.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.synthetic.log: No such file or directory
FAIL: cannot read test input procnfs
procnfs
not ok 15 - XFAIL: procnfs # TODO - If test is not an expected failure, please remove procnfs from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.procnfs.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.procnfs.log: No such file or directory
FAIL: cannot read test input lustre
lustre
not ok 16 - XFAIL: lustre # TODO - If test is not an expected failure, please remove lustre from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.lustre.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.lustre.log: No such file or directory
FAIL: cannot read test input lustre2_client
lustre2_client
not ok 17 - XFAIL: lustre2_client # TODO - If test is not an expected failure, please remove lustre2_client from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.lustre2_client.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.lustre2_client.log: No such file or directory
FAIL: cannot read test input lnet_stats
lnet_stats
not ok 18 - XFAIL: lnet_stats # TODO - If test is not an expected failure, please remove lnet_stats from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.lnet_stats.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.lnet_stats.log: No such file or directory
FAIL: cannot read test input procdiskstats
procdiskstats
not ok 19 - XFAIL: procdiskstats # TODO - If test is not an expected failure, please remove procdiskstats from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.procdiskstats.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.procdiskstats.log: No such file or directory
FAIL: cannot read test input hello_stream
hello_stream
not ok 20 - XFAIL: hello_stream # TODO - If test is not an expected failure, please remove hello_stream from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.hello_stream.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.hello_stream.log: No such file or directory
FAIL: cannot read test input llnl
llnl
not ok 21 - XFAIL: llnl # TODO - If test is not an expected failure, please remove llnl from list in /tmp/pc/lib/ovis-ldms/ldms-static-test-bypass
./ldms-run-static-tests.test: line 32: ldmstest/test.llnl.log: No such file or directory
./ldms-run-static-tests.test: line 33: ldmstest/test.llnl.log: No such file or directory
DONE.
```

**Comment by nichamon** [comment]
@baallan Thanks for testing it out. I tried running the `ldms-run-static-test.test` script but got no result. By the way, how to run the script, I read man pages but still have no idea what `<input_file>` referred in the man page should be.

**Comment by nichamon** [comment]
@baallan When I tried running `./ldms-run-static-tests.test -l`, I got a syntax error message at the last line.

```
./ldms-run-static-tests.test: 4: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=meminfo: not found
./ldms-run-static-tests.test: 6: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: @ENABLE_PAPI_SAMPLER_TRUE@: not found
./ldms-run-static-tests.test: 7: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: @ENABLE_SYSPAPI_SAMPLER_TRUE@: not found
./ldms-run-static-tests.test: 11: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=generic_sampler: not found
./ldms-run-static-tests.test: 14: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: @ENABLE_RAPL_TRUE@: not found
./ldms-run-static-tests.test: 18: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=tsampler: not found
./ldms-run-static-tests.test: 19: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=hfclock: not found
./ldms-run-static-tests.test: 20: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=dstat: not found
./ldms-run-static-tests.test: 22: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=loadavg: not found
./ldms-run-static-tests.test: 23: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=procinterrupts: not found
./ldms-run-static-tests.test: 24: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=procstat: not found
./ldms-run-static-tests.test: 25: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=procnetdev: not found
./ldms-run-static-tests.test: 26: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=vmstat: not found
./ldms-run-static-tests.test: 27: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=clock: not found
./ldms-run-static-tests.test: 29: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=variable: not found
./ldms-run-static-tests.test: 30: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=array_example: not found
./ldms-run-static-tests.test: 31: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=synthetic: not found
./ldms-run-static-tests.test: 32: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=procnfs: not found
./ldms-run-static-tests.test: 33: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=lustre: not found
./ldms-run-static-tests.test: 34: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=lustre2_client: not found
./ldms-run-static-tests.test: 35: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=lnet_stats: not found
./ldms-run-static-tests.test: 40: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=procdiskstats: not found
./ldms-run-static-tests.test: 42: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=hello_stream: not found
./ldms-run-static-tests.test: 43: /opt/ovis/lib/ovis-ldms/ldms-static-test-list.sh: testlist[0]=llnl: not found
./ldms-run-static-tests.test: 18: function: not found
./ldms-run-static-tests.test: usage:
./ldms-run-static-tests.test -h
./ldms-run-static-tests.test -l
        -h produces help message
        -l produces list of enabled plugins
See man ldms-static-test and run-static-tests.sh for details.
./ldms-run-static-tests.test: 27: Syntax error: "}" unexpected
```

Could you give some pointers on how to run the static tests? Thanks!

**Comment by baallan** [comment]
@nichamon merging this should be fine. It looks like the other problems with ./ldms-run-static-tests.test are from unrelated changes to configure.ac that simplified some of the configure options.

One of our goals (not yet quite possible) is to extend the PR/pull testing to include 'make check' and 'make installcheck' with all the generic test configure args enabled. (similar to the build checks you're adding/have added recently).

**Comment by tom95858** [comment]
@baallan, @nichamon I think there are parallel efforts going on here. There is a repository ./ldms-test that has containerized unit, functional, and system level regression tests. We should coordinate on expanding those test cases instead of creating/maintaining a separate test infrastructure.

**Comment by baallan** [comment]
@tom95858 we should get a meeting and some presentations and some planning on the calendar after the holiday. 
The two test "infrastructures", if you want to call them that, are (thus far) for meeting different (perhaps slightly overlapping) requirement sets.

**Pull request merged**
