### PR TITLE
fix double cleanup() of whatever source

### PR DESCRIPTION
**Pull request by baallan**
At least one way to invoke double cleanup and assorted memory
errors is to invoke daemon_exit in a script.
This protects cleanup with a mutex and a 'cleaned' flag.

### CODE REVIEW

**Comment by nichamon** [comment]
@baallan Could you explain the symptom? Did multiple threads call cleanup() due to a SIGTERM/SIGKILL?

**Comment by baallan** [comment]
send the daemon_exit command with controller or ldmsctl and look at the daemon with valgrind.

**Comment by tom95858** [comment]
@baallan, I cannot reproduce this using either valgrind or gdb. I only see it being called once. @nichamon and I looked at the code and the only way it is called is from the main thread or through the signal handler. But even if it could be reproduced, using a mutex when a process is exiting can result in a hang because the memory in which the mutex is located could be unmapped (i.e. contain garbage). Could you be more specific about the symptom?

**Comment by tom95858** [comment]
@baallan, if it's in 'main', then it's probably. fine. But everything in the process is actually mapped using mmap. You can see them if you look in /proc/<pid>/maps. When the process is exiting, all of those maps are going away. The heap memory, etc...all mapped. The order in which those maps are undone is not defined. In main, you are probably fine, but in the shared libraries, perhaps not. But I'm still asking ... what symptom is this actually fixing? Does it SEGV or just give valgrind heartburn?

**Comment by baallan** [comment]
@tom95858 valgrind gets very clear heartburn and often (but of course not always) w/out valgrind we get an assert or seg fault usually around one of the rbt trees..

**Comment by tom95858** [comment]
@baallan confirms that this happens in his test script when he issues the daemon_exit command and then concurrently sends SIGTERM.

**Pull request merged**
