### PR TITLE
zap_rdma omnipath workaround

### PR DESCRIPTION
**Pull request by narategithub**
omnipath evidently does not deliver all completions. This series of commits contain zap_rdma workaround for omnipath and zap_rdma debug log improvements introduced when debugging zap_rdma over omnipath.

### CODE REVIEW

**Comment by tom95858** [comment]
I would like this to be tested at "scale" on real Infiniband (i.e. not Pathscale), and iWarp. This change is fairly large and I'm concerned that we might regress OFA compliant providers.

**Comment by narategithub** [comment]
Sure.

**Comment by narategithub** [comment]
@tom95858 I experienced a dead lock inside `librdmacm.so:rdma_destroy_id()` on both iWarp and IB hardware. I'm closing this pull request + debugging it. I'll re-open this again when it passed the scale test.

**Comment by narategithub** [comment]
- This has passed a sampler+L1 flap test at scale on Mellanox IB and Chelsio iWarp hardware.
- Still waiting for omnipath test results.

**Comment by narategithub** [comment]
@tom95858 From the latest logs that @baallan sent to me, I believe this pull request is good to go. The passive-side (samplers) memory leak that happened in both zap_rdma and zap_sock cases are a separate issue that is addressed in #548.

**Pull request merged**
