### PR TITLE
zap thread endpoint assignment with number of endpoints

### PR DESCRIPTION
**Pull request by narategithub**
When all threads are busy and zap reached the maximum number of thread count, assign a new endpoint to the thread with the least number of endpoints.

### CODE REVIEW

**Comment by narategithub** [comment]
@tom95858,
Use the following command to fetch & create 1065 branch in your local tree
```
git fetch https://github.com/ovis-hpc/ovis refs/pull/1065/head:1065
```

**Comment by narategithub** [comment]
tagging Jim @valleydlr

**Comment by tom95858** [comment]
@narategithub is this push request made obsolete by the newer pull request, or is it a dependency?

**Comment by narategithub** [comment]
@tom95858 Nichamon included this in `nichamon/release-4.3.10`. Shall I remove the 'draft' so that you can merge into master branch?

**Comment by narategithub** [comment]
@tom95858 it can now be merged.

**Comment by narategithub** [comment]
Close this in favor of #1071 .

**Pull request closed without merging**
