### PR TITLE
Remove the logic that supports multiple lookup on a set

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
@tom95858 I have removed the logic that supports multiple lookups on a set. I left the LOOKUP_SET_INFO alone, i.e., an application can call lookup with the LOOKUP_SET_INFO flag. Actually I would like to remove the whole thing out and change ldms_xprt_dir() so that it always delivers dir_upd.

With this change, if a producer looks up an existing set, the producer will keep trying to look up the set because the set is in the START state and LDMSD will print the error message that the set exists repeatedly. I could turn off the repeated error message.

I have sniff tested the change but not at scale.

**Comment by nichamon** [comment]
@tom95858 I have tested that with 2 producers pointing to the same set and 2-level aggregation. I tested the following scenarios.
The 2 sampler daemons were killed one-by-one.
The 2 sampler daemons were killed at the same time.
The 1st-level aggregator was killed while the 2 sampler daemons and the 2nd-level aggregator were running.
The 2 sampler daemons were killed and then the 2nd-level aggregator was killed.

There were no crashes.

**Comment by baallan** [comment]
@nichamon rebuilding on stria, there's an function that could return a random error code even though it succeeded. static int send_req_cancel_push(struct ldms_rbuf_desc *r)
ldms_xprt.c:3333 or thereabouts needs rc initialized to zero.
Please patch.

I'm also working on testing your actual patch.

**Comment by baallan** [comment]
@nichamon I tried this + pr356 on stria and the l1 no longer crashes when the samplers all exit. For a limited number of cases tried, no sets linger either after sampler daemons are all gone.

I note that "ldms_ls -x rdma ... $sampler_daemon" still crashes as it exits with no obvious explanation suggested by valgrinding ldms_ls.

**Comment by nichamon** [comment]
> @nichamon rebuilding on stria, there's an function that could return a random error code even though it succeeded. static int send_req_cancel_push(struct ldms_rbuf_desc *r)
> ldms_xprt.c:3333 or thereabouts needs rc initialized to zero.
> Please patch.
> 
> I'm also working on testing your actual patch.

@baallan I have created a patch #363 for the uninitialized variable warning/error. It is irrelevant from this patch. Have you seen the problem before? I wonder why it has just been unearthed.

**Comment by nichamon** [comment]
> @nichamon I tried this + pr356 on stria and the l1 no longer crashes when the samplers all exit. For a limited number of cases tried, no sets linger either after sampler daemons are all gone.
> 
> I note that "ldms_ls -x rdma ... $sampler_daemon" still crashes as it exits with no obvious explanation suggested by valgrinding ldms_ls.

@baallan  You need to provide more info about the crash, e.g., valgrind log or gdb core dump. Did you give -v or -l when you started ldms_ls.

**Comment by baallan** [comment]
crash occurs with or without -l -v, but not every single time. looking like a race.

**Comment by baallan** [comment]
seg fault reported in gdb:
```
#0  0x000040002118e780 in ibv_get_cq_event () from /lib64/libibverbs.so.1
#1  0x00004000000651e0 in cq_thread_proc (arg=<optimized out>) at zap_rdma.c:1204
#2  0x0000400000607c48 in start_thread (arg=0x40002159f200) at pthread_create.c:309
#3  0x00004000001ef600 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:91
```

all threads dump:



```
Thread 8 (Thread 0x4000217af200 (LWP 128469)):
#0  0x00004000001ef7d4 in __GI_epoll_pwait (epfd=epfd@entry=8, events=events@entry=0x4000217ae8d8, maxevents=maxevents@entry=16, 
    timeout=timeout@entry=-1, set=set@entry=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:48
#1  0x00004000001ef528 in epoll_wait (epfd=epfd@entry=8, events=events@entry=0x4000217ae8d8, maxevents=maxevents@entry=16, timeout=timeout@entry=-1)
    at ../sysdeps/unix/sysv/linux/generic/epoll_wait.c:27
#2  0x0000400000064100 in cm_thread_proc (arg=0x8) at zap_rdma.c:1732
#3  0x0000400000607c48 in start_thread (arg=0x4000217af200) at pthread_create.c:309
#4  0x00004000001ef600 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:91

Thread 7 (Thread 0x40002159f200 (LWP 128468)):
#0  0x000040002118e780 in ibv_get_cq_event () from /lib64/libibverbs.so.1
#1  0x00004000000651e0 in cq_thread_proc (arg=<optimized out>) at zap_rdma.c:1204
#2  0x0000400000607c48 in start_thread (arg=0x40002159f200) at pthread_create.c:309
#3  0x00004000001ef600 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:91

Thread 6 (Thread 0x40000110f200 (LWP 128465)):
#0  0x00004000001ba9d4 in nanosleep () at ../sysdeps/unix/syscall-template.S:83
#1  0x00004000001ba688 in __sleep (seconds=0, seconds@entry=60) at ../sysdeps/unix/sysv/linux/sleep.c:137
#2  0x00004000000a7cd0 in delete_proc (arg=<optimized out>) at ldms.c:2665
#3  0x0000400000607c48 in start_thread (arg=0x40000110f200) at pthread_create.c:309
#4  0x00004000001ef600 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:91

Thread 5 (Thread 0x400000eff200 (LWP 128464)):
#0  0x000040000060c008 in __pthread_cond_wait (cond=0x430290, mutex=0x430260) at pthread_cond_wait.c:153
#1  0x00004000001fc664 in __pthread_cond_wait (cond=<optimized out>, mutex=<optimized out>) at forward.c:149
#2  0x00004000004e21cc in zap_event_thread_proc (arg=0x430250) at zap.c:691
#3  0x0000400000607c48 in start_thread (arg=0x400000eff200) at pthread_create.c:309
#4  0x00004000001ef600 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:91

Thread 4 (Thread 0x400000cef200 (LWP 128463)):
#0  0x000040000060c008 in __pthread_cond_wait (cond=0x4301d0, mutex=0x4301a0) at pthread_cond_wait.c:153
#1  0x00004000001fc664 in __pthread_cond_wait (cond=<optimized out>, mutex=<optimized out>) at forward.c:149
#2  0x00004000004e21cc in zap_event_thread_proc (arg=0x430190) at zap.c:691
#3  0x0000400000607c48 in start_thread (arg=0x400000cef200) at pthread_create.c:309
#4  0x00004000001ef600 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:91

Thread 3 (Thread 0x400000adf200 (LWP 128462)):
#0  0x000040000060c008 in __pthread_cond_wait (cond=0x430110, mutex=0x4300e0) at pthread_cond_wait.c:153
#1  0x00004000001fc664 in __pthread_cond_wait (cond=<optimized out>, mutex=<optimized out>) at forward.c:149
#2  0x00004000004e21cc in zap_event_thread_proc (arg=0x4300d0) at zap.c:691
#3  0x0000400000607c48 in start_thread (arg=0x400000adf200) at pthread_create.c:309
#4  0x00004000001ef600 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:91

Thread 2 (Thread 0x4000008cf200 (LWP 128461)):
#0  0x000040000060c008 in __pthread_cond_wait (cond=0x430050, mutex=0x430020) at pthread_cond_wait.c:153
#1  0x00004000001fc664 in __pthread_cond_wait (cond=<optimized out>, mutex=<optimized out>) at forward.c:149
#2  0x00004000004e21cc in zap_event_thread_proc (arg=0x430010) at zap.c:691
---Type <return> to continue, or q <return> to quit---
#3  0x0000400000607c48 in start_thread (arg=0x4000008cf200) at pthread_create.c:309
#4  0x00004000001ef600 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:91

Thread 1 (Thread 0x400000037c80 (LWP 128460)):
#0  0x000040000018d1ec in _int_free (av=0x400000290530 <main_arena>, p=0x435480, have_lock=0) at malloc.c:3925
#1  0x00004000212a5be0 in __trans_list_clear () from /lib64/libnl-3.so.200
#2  0x000040000000e9e0 in _dl_fini () at dl-fini.c:253
#3  0x000040000014879c in __run_exit_handlers (status=status@entry=0, listp=0x4000002904e8 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:77
#4  0x00004000001487c4 in __GI_exit (status=status@entry=0) at exit.c:99
#5  0x0000000000403ddc in main (argc=<optimized out>, argv=<optimized out>) at ldms_ls.c:1034
(gdb) 
```

**Comment by baallan** [comment]
@nichamon nothing else going on on the sampler daemon (other than samples possibly being updated) while ldms_ls is crashing.

**Pull request merged**
