### PR TITLE
Fixes in ldmsd_request.py

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
@tom95858 It turned out that I can rebase your changes on top of the set_sec_mod fix without any conflicts. 

I marked this draft because I found more leaks by calling `ldmsd_req_attr_str_value_get_by_id()` without freeing the returned `char *`. I will change it to a pull request when I go through the file.

**Comment by nichamon** [comment]
The patch passed the ldms-test suite.

**Review by tom95858 — APPROVED** [review]
@nichamon is this ready to go? It looks OK to me.

**Comment by nichamon** [comment]
> @nichamon is this ready to go? It looks OK to me.

Yes, it is ready.

**Pull request merged**
