### PR TITLE
Add enumeration compatibility checking

### PR DESCRIPTION
**Pull request by narategithub**
This commit add a github action checking that the values of enumerations
in `.github/enum-check/ovis-4.3.3-enum.list` are preserved and
compatible with OVIS-4.3.3.

### CODE REVIEW

**Comment by tom95858** [comment]
Can we extend this to include checks for 4.3.4 <-> 4.3.5 <-> 4.3.6?

**Comment by narategithub** [comment]
Sure. I'll do it tonight.

**Comment by narategithub** [comment]
@tom95858,

I think I got a little confused with your request :dizzy_face: The action checks the preservation of enums from 4.3.3 against the code in the (future) pull request. My guess is that you want the same enum check against the (future) pull request with 4.3.4, 4.3.5 and 4.3.6 too, right?

Anyway, the script is also capable of listing all enumeration values ... so with `diff`, the changes in enumerations from 4.3.3<-->4.3.4<-->4.3.5<-->4.3.6 are as follows:

(We can ignore the `*_LAST` and `LDMSD_NOTSUPPORT_REQ` since they're the last enum that are subject to change. The `+` new entries should be fine, but the `-` removed or modified entries may break the network protocol compatibility).

4.3.3 --> 4.3.4
```diff
--- 4.3.3.list  2021-01-20 03:31:28.694040211 +0000                              
+++ 4.3.4.list  2021-01-20 03:26:17.045994232 +0000                              
@@ -507,6 +507,7 @@                                                              
 KLDMS_REQ_PUBLISH_SET=2                                                         
 KLDMS_REQ_UNPUBLISH_SET=3                                                       
 KLDMS_REQ_UPDATE_SET=4                                                          
+LDMSD_ATTR_AUTH=35                                                              
 LDMSD_ATTR_AUTO_INTERVAL=31                                                     
 LDMSD_ATTR_AUTO_SWITCH=28                                                       
 LDMSD_ATTR_BASE=18                                                              
@@ -517,7 +518,7 @@                                                              
 LDMSD_ATTR_INSTANCE=7                                                           
 LDMSD_ATTR_INTERVAL=2                                                           
 LDMSD_ATTR_JSON=26                                                              
-LDMSD_ATTR_LAST=35                                                              
+LDMSD_ATTR_LAST=37                                                              
 LDMSD_ATTR_LEVEL=20                                                             
 LDMSD_ATTR_MATCH=11                                                             
 LDMSD_ATTR_METRIC=15                                                            
@@ -532,6 +533,7 @@                                                              
 LDMSD_ATTR_PUSH=23                                                              
 LDMSD_ATTR_REC_LEN=25                                                           
 LDMSD_ATTR_REGEX=4                                                              
+LDMSD_ATTR_RESET=36                                                             
 LDMSD_ATTR_SCHEMA=14                                                            
 LDMSD_ATTR_STREAM=34                                                            
 LDMSD_ATTR_STRING=16                                                            
@@ -543,6 +545,10 @@                                                             
 LDMSD_ATTR_UDATA=17                                                             
 LDMSD_ATTR_UID=32                                                               
 LDMSD_ATTR_XPRT=8                                                               
+LDMSD_AUTH_ADD_REQ=2560                                                         
+LDMSD_AUTH_DEL_REQ=2561                                                         
+LDMSD_CFGOBJ_AUTH=5                                                             
+LDMSD_CFGOBJ_LISTEN=4                                                           
 LDMSD_CFGOBJ_PRDCR=1                                                            
 LDMSD_CFGOBJ_STRGP=3                                                            
 LDMSD_CFGOBJ_UPDTR=2                                                            
@@ -574,13 +580,14 @@                                                            
 LDMSD_LDEBUG=0                                                                  
 LDMSD_LERROR=3                                                                  
 LDMSD_LINFO=1                                                                   
+LDMSD_LISTEN_REQ=1550                                                           
 LDMSD_LLASTLEVEL=6                                                              
 LDMSD_LNONE=-1                                                                  
 LDMSD_LOGROTATE_REQ=1544                                                        
 LDMSD_LWARNING=2                                                                
 LDMSD_NAME_MATCH_INST_NAME=0                                                    
 LDMSD_NAME_MATCH_SCHEMA_NAME=1                                                  
-LDMSD_NOTSUPPORT_REQ=2306                                                       
+LDMSD_NOTSUPPORT_REQ=2562                                                       
 LDMSD_ONESHOT_REQ=1543                                                          
 LDMSD_PLUGIN_OTHER=0                                                            
 LDMSD_PLUGIN_SAMPLER=1                                                          
@@ -599,6 +606,7 @@                                                              
 LDMSD_PRDCR_DEL_REQ=257                                                         
 LDMSD_PRDCR_HINT_TREE_REQ=264                                                   
 LDMSD_PRDCR_SET_REQ=263                                                         
+LDMSD_PRDCR_SET_STATE_DELETED=4                                                 
 LDMSD_PRDCR_SET_STATE_LOOKUP=1                                                  
 LDMSD_PRDCR_SET_STATE_READY=2                                                   
 LDMSD_PRDCR_SET_STATE_START=0                                                   
@@ -617,6 +625,7 @@                                                              
 LDMSD_PRDCR_TYPE_ACTIVE=0                                                       
 LDMSD_PRDCR_TYPE_LOCAL=2                                                        
 LDMSD_PRDCR_TYPE_PASSIVE=1                                                      
+LDMSD_PRDCR_UNSUBSCRIBE_REQ=266                                                 
 LDMSD_RECORD_LEN_ADVICE_REQ=1546                                                
 LDMSD_SETGROUP_ADD_REQ=2048                                                     
 LDMSD_SETGROUP_DEL_REQ=2050                                                     
@@ -632,10 +641,12 @@                                                            
 LDMSD_SMPLR_DEL_REQ=1025                                                        
 LDMSD_SMPLR_START_REQ=1026                                                      
 LDMSD_SMPLR_STOP_REQ=1027                                                       
+LDMSD_STREAM_CLIENT_DUMP_REQ=2307                                               
 LDMSD_STREAM_JSON=1                                                             
 LDMSD_STREAM_PUBLISH_REQ=2304                                                   
 LDMSD_STREAM_STRING=0                                                           
 LDMSD_STREAM_SUBSCRIBE_REQ=2305                                                 
+LDMSD_STREAM_UNSUBSCRIBE_REQ=2306                                               
 LDMSD_STRGP_ADD_REQ=512                                                         
 LDMSD_STRGP_DEL_REQ=513                                                         
 LDMSD_STRGP_METRIC_ADD_REQ=519                                                  
@@ -650,6 +661,7 @@                                                              
 LDMSD_TASK_STATE_RUNNING=2                                                      
 LDMSD_TASK_STATE_STARTED=1                                                      
 LDMSD_TASK_STATE_STOPPED=0                                                      
+LDMSD_THREAD_STATS_REQ=1549                                                     
 LDMSD_UPDTR_ADD_REQ=768                                                         
 LDMSD_UPDTR_DEL_REQ=769                                                         
 LDMSD_UPDTR_MATCH_ADD_REQ=775                                                   
@@ -665,6 +677,7 @@                                                              
 LDMSD_UPDTR_TASK_REQ=777                                                        
 LDMSD_VERBOSE_REQ=1538                                                          
 LDMSD_VERSION_REQ=1540                                                          
+LDMSD_XPRT_STATS_REQ=1548                                                       
 LDMS_CMD_AUTH=8                                                                 
 LDMS_CMD_AUTH_APPROVAL_REPLY=263                                                
 LDMS_CMD_AUTH_CHALLENGE_REPLY=262                                               
@@ -684,15 +697,19 @@                                                            
 LDMS_CMD_REQ_NOTIFY=3                                                           
 LDMS_CMD_REQ_NOTIFY_REPLY=261                                                   
 LDMS_CMD_SEND_MSG=5                                                             
+LDMS_CMD_SET_DELETE=9                                                           
+LDMS_CMD_SET_DELETE_REPLY=266                                                   
 LDMS_CMD_XPRT_PRIVATE=-2147483648                                               
 LDMS_CONTEXT_DIR=0                                                              
 LDMS_CONTEXT_DIR_CANCEL=1                                                       
-LDMS_CONTEXT_LOOKUP=2                                                           
-LDMS_CONTEXT_PUSH=6                                                             
-LDMS_CONTEXT_REQ_NOTIFY=4                                                       
-LDMS_CONTEXT_SEND=5                                                             
-LDMS_CONTEXT_UPDATE=3                                                           
-LDMS_CONTEXT_UPDATE_META=7                                                      
+LDMS_CONTEXT_LOOKUP_READ=3                                                      
+LDMS_CONTEXT_LOOKUP_REQ=2                                                       
+LDMS_CONTEXT_PUSH=7                                                             
+LDMS_CONTEXT_REQ_NOTIFY=5                                                       
+LDMS_CONTEXT_SEND=6                                                             
+LDMS_CONTEXT_SET_DELETE=9                                                       
+LDMS_CONTEXT_UPDATE=4                                                           
+LDMS_CONTEXT_UPDATE_META=8                                                      
 LDMS_DIR_ADD=2                                                                  
 LDMS_DIR_DEL=1                                                                  
 LDMS_DIR_LIST=0                                                                 
@@ -745,9 +762,18 @@                                                             
 LDMS_XPRT_EVENT_CONNECTED=0                                                     
 LDMS_XPRT_EVENT_DISCONNECTED=3                                                  
 LDMS_XPRT_EVENT_ERROR=2                                                         
-LDMS_XPRT_EVENT_LAST=5                                                          
+LDMS_XPRT_EVENT_LAST=6                                                          
 LDMS_XPRT_EVENT_RECV=4                                                          
 LDMS_XPRT_EVENT_REJECTED=1                                                      
+LDMS_XPRT_EVENT_SET_DELETE=5                                                    
+LDMS_XPRT_OP_COUNT=7                                                            
+LDMS_XPRT_OP_DIR_REP=5                                                          
+LDMS_XPRT_OP_DIR_REQ=4                                                          
+LDMS_XPRT_OP_LOOKUP=0                                                           
+LDMS_XPRT_OP_PUBLISH=2                                                          
+LDMS_XPRT_OP_SEND=6                                                             
+LDMS_XPRT_OP_SET_DELETE=3                                                       
+LDMS_XPRT_OP_UPDATE=1                                                           
 OVIS_EVENT_EPOLL=1                                                              
 OVIS_EVENT_EPOLL_TIMEOUT=3                                                      
 OVIS_EVENT_PERIODIC=4                                                           
```

4.3.4 --> 4.3.5
```diff
--- 4.3.4.list  2021-01-20 03:26:17.045994232 +0000                              
+++ 4.3.5.list  2021-01-20 03:26:21.570111057 +0000                              
@@ -879,6 +879,8 @@                                                              
 ZAP_EVENT_WRITE_COMPLETE=8                                                      
 ZAP_MAP_LOCAL=1                                                                 
 ZAP_MAP_REMOTE=2                                                                
+Z_RDMA_DEV_HFI1=1                                                               
+Z_RDMA_DEV_OTHER=0                                                              
 Z_RDMA_MSG_ACCEPT=4                                                             
 Z_RDMA_MSG_CREDIT_UPDATE=1                                                      
 Z_RDMA_MSG_REJECT=5                                                             
```

4.3.5 --> 4.3.6
```diff
--- 4.3.5.list  2021-01-20 03:26:21.570111057 +0000                              
+++ 4.3.6.list  2021-01-20 03:26:25.994225300 +0000                              
@@ -580,7 +580,7 @@                                                              
 LDMSD_LDEBUG=0                                                                  
 LDMSD_LERROR=3                                                                  
 LDMSD_LINFO=1                                                                   
-LDMSD_LISTEN_REQ=1550                                                           
+LDMSD_LISTEN_REQ=1552                                                           
 LDMSD_LLASTLEVEL=6                                                              
 LDMSD_LNONE=-1                                                                  
 LDMSD_LOGROTATE_REQ=1544                                                        
@@ -618,6 +618,7 @@                                                              
 LDMSD_PRDCR_STATE_DISCONNECTED=1                                                
 LDMSD_PRDCR_STATE_STOPPED=0                                                     
 LDMSD_PRDCR_STATE_STOPPING=4                                                    
+LDMSD_PRDCR_STATS_REQ=1550                                                      
 LDMSD_PRDCR_STATUS_REQ=260                                                      
 LDMSD_PRDCR_STOP_REGEX_REQ=262                                                  
 LDMSD_PRDCR_STOP_REQ=259                                                        
@@ -635,6 +636,7 @@                                                              
 LDMSD_SET_ORIGIN_PRDCR=2                                                        
 LDMSD_SET_ORIGIN_SAMP_PI=1                                                      
 LDMSD_SET_ROUTE_REQ=1547                                                        
+LDMSD_SET_STATS_REQ=1551                                                        
 LDMSD_SET_UDATA_REGEX_REQ=1537                                                  
 LDMSD_SET_UDATA_REQ=1536                                                        
 LDMSD_SMPLR_ADD_REQ=1024                                                        
```

And 4.3.5 --> 4.3.6 showed the `LDMSD_LISTEN_REQ` number change you mentioned the other day.

**Comment by narategithub** [comment]
@tom95858 the script now checks enumerations of the future pull requests against 4.3.3, 4.3.4, 4.3.5 and 4.3.6. However, `LDMSD_LISTEN_REQ` is dropped from the 4.3.4 and 4.3.5 check list since 4.3.6 changed its value. `LDMSD_LISTEN_REQ` is in 4.3.6 check list though. Hence, if the future pull requests change its value, the check will report an error.

**Pull request merged**
