### PR TITLE
add user and group names options for status_uid/gid

### PR DESCRIPTION
**Pull request by baallan**
This adds the ability to optionally collect names corresponding to uid and gid values, enabling analyses based on user or group name.
The library call(s) to lookup username/groupname are not repeated so long as the paired uid/gid value does not change.

### CODE REVIEW

**Comment by tom95858** [comment]
@baallan, it seem to me that this change was made only to the linux_proc_sampler and not to the app_sampler from which it is almost entirely derived. I think we should combine these two samplers and have a config option to select either notifier or streams data.

**Comment by baallan** [comment]
The combining of incompatible (but related) plugins is beyond the scope of this PR. 
We need this small revision to linux_proc_sampler to enable some of our production Q1 goals.

We can certainly have a separate discussion of the two samplers and a possible merged future. This sampler is certainly not *entirely* derived from the other. If merging/deprecating app_sampler is not in the future, I'll be happy to add the user/group name to it as well. Let's conduct our fine-grained comparison of the features and schemas of the two and then decide how to proceed.

**Comment by baallan** [comment]
fixes #1055

**Comment by tom95858** [comment]
Please update the appmon sampler with the equivalent functionality.

**Comment by baallan** [comment]
@tom95858 user/group names added to app sampler.
Also relocated the man page to be adjacent to source.

**Comment by baallan** [comment]
@tom95858 ready to merge

**Pull request merged**
