### PR TITLE
zap_fabric returns a wrong max_msg size

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
@tom95858 I marked this as a draft because I believe I don't have an access to a machine with fabric to compile and test the code.

**Comment by baallan** [comment]
@nichamon We have a transport test plan (sock, rdma, fabric) on omnipath hardware for v4.
Do patches 144-146 belong on OVIS-4 as well?
I so I can pick them into our testing source.

**Comment by nichamon** [comment]
@baallan I have created the pull requests for sock, rdma and fabric for OVIS-4, #152, #155 and #154, respectively. The zap_fabric patch has never been compiled so it would be best for someone who has access to a fabric library to try compiling it before merging it in.

**Comment by baallan** [comment]
will test asap

**Comment by baallan** [comment]
This builds on our omnipath platforms in its OVIS-4 branch incarnation.

**Comment by tom95858** [comment]
@nichamon I think this has been confirmed to build correctly, please post the pull request.

**Comment by tom95858** [comment]
@nichamon can you please mark this as done so I can merge it?

**Comment by nichamon** [comment]
@tom95858 I marked it as ready. However, it haven't been built or tested as I don't have any access to fabric.

**Pull request merged**
