### PR TITLE
update gender config example to v4

### PR DESCRIPTION
**Pull request by baallan**
updating the plugins-conf subdir of the genders systemd example to v4.

### CODE REVIEW

**Review by morrone — CHANGES_REQUESTED** [review]
The volume of new files and repetition in the contents of these files make this look a lot less like an update to "examples" than it does your local configuration settings stored in the upstream source. I do not think that is a particularly good direction to go with examples.

The Makefile.am does not appear to have been updated in this commit to include the files in the dist either.

**Comment by baallan** [comment]
@morrone  thankyou for catching the makefile omission.

**Comment by morrone** [comment]
@tom95858 the Makefile.am omission does not appear to have been addressed before landing.

**Comment by tom95858** [comment]
@morrone, sorry I was told this had been addressed and was ready for merge. @baallan  please resolve this ASAP?

**Comment by baallan** [comment]
I will add the makefile update to the same branch and open another request today. Apologies; it slipped my mind.

**Pull request merged**
