### PR TITLE
Add rdc plugin to collect AMD GPU metrics

### PR DESCRIPTION
**Pull request by miketxli**
Signed-off-by: Mike Li <Tianxinmike.Li@amd.com>

### CODE REVIEW

**Comment by baallan** [comment]
@miketxli  I've backported the amd gpu sampler to https://github.com/baallan/ovis.git branch backport_rdc derived from the OVIS-4 branch.

If you or a colleague have time and an environment to test in, please try to build (and ideally run) it and let me know what problems you find. ovis/ldms/src/sampler/rdc_sampler/Makefile.am will need some minor tweaking to find the right headers/libs.

**Comment by miketxli** [comment]
@baallan Great, let me build and test it. I'll let you know the result.

**Comment by baallan** [comment]
@miketxli Thanks for testing and letting me know the revised rdc_sampler worked with your setup.

I'm trying now to build with rocm-4.1.0 and run with mi50 and v320 based cards; the library says the RDC_FI_ECC_CORRECT_TOTAL, RDC_FI_ECC_UNCORRECT_TOTAL, and XGMI metrics are unsupported. Is this the expected behavior?

**Comment by baallan** [comment]
Is there a convenient way to tell if they are xgmi connected, perhaps in the output of rocm-smi -a?
I suspect they are not connected. The more concerning thing would be the ECC metrics; are they no longer using ecc memory?

**Comment by miketxli** [comment]
> Is there a convenient way to tell if they are xgmi connected, perhaps in the output of rocm-smi -a?
> I suspect they are not connected. The more concerning thing would be the ECC metrics; are they no longer using ecc memory?

1) Yes, rocm-smi --showtopo
2) They use different way to get those metrics. There is patch for this.  See https://github.com/RadeonOpenCompute/rdc/tree/master/ras_prebuild. You need to copy all those files in the same folder as the librdc.so. I haven't try it myself. But this will be fixed in next release.

**Comment by baallan** [comment]
Thanks for the clues. So it would show link type other than PCIE (xgmi instead?) if we had the direct connections, yes? And by next release you mean a rocm 4.3 or some other?

It seems in the meantime, I should drop the ECC metrics from the default counter set. Would you agree?

**Comment by miketxli** [comment]
> Thanks for the clues. So it would show link type other than PCIE (xgmi instead?) if we had the direct connections, yes? And by next release you mean a rocm 4.3 or some other?
> 
> It seems in the meantime, I should drop the ECC metrics from the default counter set. Would you agree?

yes to xgmi.
I think you drop ECC from default set until it is stabilized in later release. I will find out target release for you.

**Pull request merged**
