### PR TITLE
Rename libparse_stat to libldmsd_parse_stat

### PR DESCRIPTION
**Pull request by morrone**
Rename libparse_stat to libldmsd_parse_stat

Part of #71

### CODE REVIEW

**Comment by baallan** [comment]
This is not a convenience library.
libparse_stat is intended for use by more than one sampler. renaming it ldms_parse_stat rather than parse_stat is the appropriate fix. The libdstat plugin is dependent on libparse_stat; the parse functions are not copied into the dstat plugin binary.

**Comment by morrone** [comment]
> This is not a convenience library.
> libparse_stat is intended for use by more than one sampler. 

Those two statements seem unrelated to me.  Could you please elaborate? A convenience library fully supports (if not encourages) use by more than one sampler.

**Comment by morrone** [comment]
You probably mean that you want those libraries to be dynamically linked to to parse_stat?

**Comment by baallan** [comment]
I don't mean to say "I want those libraries to be dynamically linked". I'm telling you libparse_stat is dynamically linked by plugins, so it needs to be installed. Run ldd and nm -u on an installed ovis-ldms/libdstat.so and you will see.

**Comment by morrone** [comment]
It will work as I've done it as well. Then it doesn't need to be installed in libdir, where we put things when we desire to share the code _outside_ of the project rather than inside the project.

You sound attached to the current approach though, so I'll go with a rename.

**Comment by morrone** [comment]
Actually, I'm not entirely sure if I was clear: my approach works because the convenience library is statically linked into the plugin, and therefore eliminates a dynamic library at run time.

Sure, plugins would be slightly larger than they need to be, but I think that is reasonable for small support libraries like this.

But in the interest of expediency, I will still submit a patch that just does a rename.

**Comment by morrone** [comment]
I updated the PR to do a rename rather that changing it to a convenience library.

**Comment by tom95858** [comment]
This library is only used by one plugin. I would inclined to not make this a library at all and just link it statically with the plugin that uses it. If in the future another user comes alone we can make a library and either ship it or bind it non-shared.

**Comment by morrone** [comment]
> This library is only used by one plugin. I would inclined to not make this a library at all and just link it statically with the plugin that uses it. If in the future another user comes alone we can make a library and either ship it or bind it non-shared.

That was my original approach in this PR, so I at least am on board with that.

**Comment by morrone** [comment]
OK, the PR has been updated back to the original noinst library/statically linked approach.

**Comment by tom95858** [comment]
This has been cherry-picked into OVIS-4

**Pull request closed without merging**
