### PR TITLE
Remove an erroneous return line in stream_republish_cb

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
@tom95858 The return line should have been removed in my previous patch. I didn't push all the changes in my local branch to the remote one, and the change was left in my local branch.

**Review by tom95858 — CHANGES_REQUESTED** [review]
You'll need t rebase this change.

**Comment by nichamon** [comment]
I'm closing this because the logic has been fixed in #703 .

**Comment by nichamon** [comment]
@tom95858 I have removed the 3 lines.

**Pull request merged**
