### PR TITLE
adding munge to genders init scripts

### PR DESCRIPTION
**Pull request by baallan**
also fixing lack of env expansion in log gender value for better debugging control.

### CODE REVIEW

**Comment by baallan** [comment]
This is in testing at SNL.

**Comment by tom95858** [comment]
Hi @baallan do you want this merged or is this a work in progress?

**Comment by baallan** [comment]
still in testing. we've proven locally the added code didn't break the non-munge auth, but we haven't yet proved the munge paths to all work correctly. lots of other things being tested before.

**Comment by baallan** [comment]
@tom95858 please merge this at last.

**Pull request merged**
