### PR TITLE
fix #773 unreleased lock in __send_lookup_reply

### LINKED ISSUE #773: Potential error(e.g., deadlock ) due to the unreleased lock &set->lock (CWE-667)
Dear developers, thank you for your checking! It seems that the lock `&set->lock` may not be released correctly if the method `__send_lookup_reply` when the` !msg` is satisfied and the control flow goes to  `err_0` that does not release the lock &set->lock. Should it be a real bug? I think the fix is to insert `pthread_mutex_unlock(&set->lock);` in the branch of` !msg`.

https://github.com/ovis-hpc/ovis/blob/84513760731014c170104ff11608867b62096b58/ldms/src/core/ldms_xprt.c#L1274

The process is detailed as below.
```
static int __send_lookup_reply(struct ldms_xprt *x, struct ldms_set *set,
			       uint64_t xid, int more)
{
	...;
	pthread_mutex_lock(&x->lock); // acquire the lock x->lock first
	
	...;

	pthread_mutex_lock(&set->lock);  // acquire the lock set->lock
	...;
	if (!msg) {  // the condition may be satisfied
		rc = ENOMEM;
		goto err_0; // goto err_o mistakenly with unrelased the lock set->lock
	}

	...;
	pthread_mutex_unlock(&set->lock);
	...;
	if (zerr != ZAP_ERR_OK) {
		...;
		goto err_0; // correctly since the lock set->lock has been released
	}
	pthread_mutex_unlock(&x->lock);
	...;
	return 0;
 err_0:
	pthread_mutex_unlock(&x->lock); 
	return rc;
}
```

Best,

### PR DESCRIPTION
**Pull request by baallan**
fixes related error logging in caller also.

### CODE REVIEW

**Comment by tom95858** [comment]
@nichamon could you please review this

**Comment by nichamon** [comment]
@tom95858 The fixes are legit.

@baallan Thanks for catching the missing unlock and the wrong error code variable. What do think about merging the two error messages, the `zap_send` synchronously errors and the local error code? The two messages are related. If `zap_send()` doesn't fail, the client will receive the error. In this case, the `zap_send()` failed so you logged the error that triggers the `zap_send()`. Shall we log the error something like 
```
x->log("%s: x %p: zap_send synchronously errors '%s' while sending the error %d (%s)\n",
				__func__, x, zap_err_str(zerr), rc, STRERROR(rc));
```

**Comment by baallan** [comment]
@nichamon done combining the messages.

**Comment by baallan** [comment]
@nichamon looks like the build fail on ubuntu is provoked by github and not the code change.

**Comment by nichamon** [comment]
> @nichamon looks like the build fail on ubuntu is provoked by github and not the code change.

@baallan Github didn't even run ./autogen.sh yet. It failed when it tried to fetch the code. Could you try to re-run the test again?

**Review by nichamon — APPROVED** [review]

**Comment by baallan** [comment]
@nichamon I tried, and there is no page which presents me with an option to rerun the check or the entire workflow; I presume this is due to my role in the project being 'outside collaborator'.

**Comment by nichamon** [comment]
@baallan What works for me in this situation is to do `git commit --amend` without changing the code and the commit message. Could you please give it a try?

On your local machine,
```
> git checkout <branch name>
> git commit --amend # Save and close the editor without changing anything
> git push -f <remote> HEAD
```
You would need to _force_ push the HEAD to the remote branch because `git commit --amend` will always change the TIP of the branch locally.

**Comment by baallan** [comment]
@nichamon the re-run checks hack that seems to work is to close and immediately reopen the issue, doable with  UI buttons, though undocumented.

**Comment by baallan** [comment]
@nichamon is there anything else you would like changed before you can approve this one?

**Review by nichamon — APPROVED** [review]

**Comment by nichamon** [comment]
@baallan I approved it yesterday before you resolved the Github action fail. I just approved it again just in case.

**Pull request merged**
