### PR TITLE
trap/fix use of uninit pointer/ins in ldmsctl:__handle_cmd

### PR DESCRIPTION
**Pull request by baallan**
bug picked up by gcc 4.8.5 -Wall

### CODE REVIEW

**Review by tom95858 — COMMENTED** [review]
@baallan, this code is broken, but although your change may silence the static analysis tool, it didn't fix the error. If you'll notice resp comes from recv_buf which is pulled off of the recv_buf_q, copied into lbuf, and then freed on line 1995, so resp->err_msg is pointing to freed memory. @nichamon, please look at this for an actual fix. I think that in the event that there is an error,  we'll want to do something different, probably inside the while(1).

**Comment by nichamon** [comment]
@tom95858 I's working on this patch shortly because I swapped my attention to the dir_update path last week. I'll be back on this tonight.

**Comment by baallan** [comment]
@nichamon please close this PR after you create a better PR.

**Comment by nichamon** [comment]
The fix is #517 .

**Pull request closed without merging**
