### PR TITLE
add missing file cleanup from test_sps.sh

### PR DESCRIPTION
**Pull request by baallan**
this removes test output files which in some circumstances make distcheck fail and block other unrelated pull requests.

### CODE REVIEW

**Comment by baallan** [comment]
@tom95858 has the functionality of ldms_sps been moved into another functionality of the stream/xprt API that simplifies the numerously duplicated and complex chunks of stream publishing code that are going into kokkos, calipre, darshan, etc?

**Comment by tom95858** [comment]
Please remove the ldms_sps library and the associated files.

**Comment by baallan** [comment]
@tom95858 I have removed the ldms_sps library from the ldmsd/ directory and cleaned up related problems with distclean.

**Comment by baallan** [comment]
@tom95858 please merge the revised #825. It is needed for scale testing on voltrino and eclipse.

**Pull request merged**
