### PR TITLE
move some examples files from /etc to /share

### PR DESCRIPTION
**Pull request by oceandlr**
Re issue #310 

Moved aries_mmr_set_configs and hello_sampler_util from XXX/etc to XXX/share/doc/ovis-ldms-X.Y.Z/examples

### CODE REVIEW

**Comment by oceandlr** [comment]
BEFORE accepting this:
@valleydlr -- are you ok with the move of aries_mmr_set_configs? Do you use it in place?
@tom95858 @morrone -- in #310, @morrone was against the install-data-local ... I have kept it as is. If we want this change then there are other places that should change as well.
@tom95858 -- will a move at this point break with any standard policy?

**Comment by oceandlr** [comment]
@baallan I based this off of XXX/ovis/ldms/src/third-plugins/my_plugin/Makefile.am and ovis/ldms/src/third-plugins/my_plugin/scripts/Makefile.am. Did I misread those?

BTW, it looked to me at the top level configure that $(docdir) gets defined, so it is redefined in those third-plugin places. This is why I used $(datadocdir) as my local name. Am in interpreting this correctly, and if so, should we do similarly here in third-plugins?

**Comment by baallan** [comment]
@oceandlr the third-plugin subdirs are standalone projects in themselves, so things differ. The naming I suggest follows the rule $top/ldms/Makefile.am:install-data-local

**Comment by oceandlr** [comment]
updated to address @baallan requested change (sorry if that should go in the thread elsewhere)
Please all still see the 2nd comment for review considerations...

**Comment by baallan** [comment]
@oceandlr https://www.gnu.org/software/automake/manual/html_node/Standard-Directory-Variables.html
is the baseline supported by automake. The use of PACKAGE_VERSION instead of just PACKAGE is a common extension used to avoid conflicts when multiple major versions may be installed on the same system.

**Comment by tom95858** [comment]
@oceandlr, @baallan: is everyone happy with this change?

**Comment by oceandlr** [comment]
@valleydlr should weigh in on the move since I don't know if he is expecting the Aries config files to be in a particular place.
Also do you @tom95858 have any option on the install-data-local that @morrone was against? However, I don't know what the alternative would be and if we do want to change it then we should change elsewhere, so maybe that should just be a different change, if we want to go that route.

**Comment by morrone** [comment]
> @valleydlr should weigh in on the move since I don't know if he is expecting the Aries config files to be in a particular place.
> Also do you @tom95858 have any option on the install-data-local that @morrone was against? However, I don't know what the alternative would be and if we do want to change it then we should change elsewhere, so maybe that should just be a different change, if we want to go that route.

I don't have a problem with cleaning that up some time later. FYI, I documented the alternative to using custom install-data-local hooks in issue #310.

**Comment by valleydlr** [comment]
I have no problem with this. The aries configs can be copied from one place just as well as another.

**Comment by oceandlr** [comment]
ok @tom95858, ready to go

**Pull request merged**
