### PR TITLE
[FIX] change schema name to aggregate data

### PR DESCRIPTION
**Pull request by sindhu-106**

### CODE REVIEW

**Comment by morrone** [comment]
I think this PR needs to be reworked. Some of these commits are already landed (and one erroneously attributed to _me_ as the author). Did you only mean to request that the "[FIX] change metrics data format" commit be added?

**Review by morrone — CHANGES_REQUESTED** [review]
PR needs to be rebased/reworked.

**Comment by tom95858** [comment]
@sindhu-106 could you please address @morrone comments?

**Comment by tom95858** [comment]
@sindhu-106 ... ping

**Comment by morrone** [comment]
On @VanshIntel's advice, closing this PR.

**Pull request closed without merging**
