### PR TITLE
Fix bugs in the slurm_sampler2 plugin

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
The PR depends on #1028.

**Comment by narategithub** [comment]
This PR passed the accompanied test script in https://github.com/ovis-hpc/ldms-test/pull/31

**Comment by tom95858** [comment]
@nichamon, could you please rebase this? Isn't the LDMS record size API already in the tree?

**Comment by nichamon** [comment]
> @nichamon, could you please rebase this? Isn't the LDMS record size API already in the tree?

I just rebased.

The Slurm sampler2 commit depends on the API. I included the LDMS  API commit to making the PR buildable.

**Pull request merged**
