### PR TITLE
ZFS LDMS samplers from LLNL

### PR DESCRIPTION
**Pull request by carbonneau1**
Added 3 plugins for ZFS:

1) zfs_topvdevs
2) zfs_leafvdevs
3) zfs_zpool

### CODE REVIEW

**Comment by tom95858** [comment]
@carbonneau1, @morrone do you guys want to make this automatically enabled if the libzfs headers are present or keep it the way it is with the --enable-zfs?

**Comment by morrone** [comment]
> do you guys want to make this automatically enabled if the libzfs headers are present or keep it the way it is with the --enable-zfs?

@tom95858  I believe that it already automatically enables the build if libzfs is found and neither "--enable-zfs" nor "--disable-zfs" are specified. That is what this should handle:

> AM_CONDITIONAL([ENABLE_ZFS], [test "x$enable_zfs" != xno -a "x$HAVE_ZFS" = xyes])

**Comment by tom95858** [comment]
@morrone, ok this is good for top of tree right?

**Comment by morrone** [comment]
> @morrone, ok this is good for top of tree right?

Yes, it is ready for top of tree.

**Pull request merged**
