### PR TITLE
Make ldmsd_plugattr report log messages to the application's default log

### PR DESCRIPTION
**Pull request by nichamon**
The patch is to fix build problems of stand-alone application in the project that uses the library.

### CODE REVIEW

**Comment by nichamon** [comment]
@morrone Could you give this a try?

**Comment by morrone** [comment]
Yes, it does compile now. Thanks!

**Comment by nichamon** [comment]
> Yes, it does compile now. Thanks!

@morrone  Thanks for trying it out!

**Comment by baallan** [comment]
I will look into this. 

The plugattr library is utilities for processing configuration values (all during the config method). As such, the messages should really be controlled by the debug level at which config-statement processing is being handled, not by the sampler-specific logging level which is appropriate during sample() and the other methods.

I have a patch already for the standalone program references to logging.

**Pull request merged**
