### PR TITLE
Fix the daemon_exit handler in ldmsd_communicator.py

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
I tested the patch by using the daemon_exit command in ldmsd_controller to make an ldmsd exit. It worked.

@nick-enoent Could you take a look at this patch? I could not add you as a reviewer. :(

**Comment by nick-enoent** [comment]
> I tested the patch by using the daemon_exit command in ldmsd_controller to make an ldmsd exit. It worked.
> 
> @nick-enoent Could you take a look at this patch? I could not add you as a reviewer. :(

@nichamon Thanks for taking care of this! This looks good to me.

**Comment by tom95858** [comment]
@nichamon, this is currently marked WIP, can you make it "ready"

**Comment by nichamon** [comment]
> @nichamon, this is currently marked WIP, can you make it "ready"

I just changed it. I don't know why it was a draft.

**Pull request merged**
