### PR TITLE
Retire the genders configuration method.

### PR DESCRIPTION
**Pull request by morrone**
I figured I would start the conversation about when we can remove the genders configuration method from the main ovis tree. I imagine it will require some planning.

### CODE REVIEW

**Comment by baallan** [comment]
We can retire genders when maestro is an equally functional and similarly compact equivalent, which I would hope would be soon but isn't yet.

**Comment by morrone** [comment]
> We can retire genders when maestro is an equally functional and similarly compact equivalent, which I would hope would be soon but isn't yet.

Could you perhaps move that out-of-tree? Maintain that as part of your local configuration management system instead?

We'll need to work this out soon, because my TOSS4 packages don't currently include these files, and I really don't want them all filling up /etc/ldms and such when they don't apply to anything we do here.

**Comment by tom95858** [comment]
@baallan, @morrone, where are we on this. I would like to get the genders code out of the tree. It is not my view that whether or not and if genders is retired is dependent on missing capabilities from other tools (e.g. Maestro).

**Comment by tom95858** [comment]
@morrone, how time critical is this? You can exclude the undesirable files in the .spec file correct? I realize that is a giant pain.

**Comment by morrone** [comment]
> @morrone, how time critical is this? You can exclude the undesirable files in the .spec file correct? I realize that is a giant pain.

I have, in fact, been removing those files in the TOSS4 spec file all along. So far this hasn't seemed to effect anyone. But I am concerned if people aren't prepared for that.

**Comment by baallan** [comment]
snl admins would strongly like to be using (for toss3) ldms rpms 'out of the box' from the llnl packaging with the existing genders support. Toss4 seems to be a reasonable cut-over point to drop genders and shifting to maestro-based configuration, but it looks like we expect to be using toss3 until the retirement of our last TLCC2 system (still 1-2 years out).

**Comment by morrone** [comment]
> snl admins would strongly like to be using (for toss3) ldms rpms 'out of the box' from the llnl packaging with the existing genders support. Toss4 seems to be a reasonable cut-over point to drop genders and shifting to maestro-based configuration, but it looks like we expect to be using toss3 until the retirement of our last TLCC2 system (still 1-2 years out).

OK. And TOSS3 is basically in critical-fixes-only mode at this late stage of its life. I don't think we should expect to have any new LDMS features in TOSS3 releases.

So I think that landing this commit on OVIS-4 makes sense.

If the ldms in TOSS3 needs some critical security bug fixed, I am certainly willing to make a branch of an older TOSS ldms release and backport a reasonable patch.

**Comment by baallan** [comment]
@morrone We fully expect that ldmsd will behave the same features for a given release whether running on toss4 or toss3. We run center-wide integrated monitoring and will continue to need and contribute innovations in plugins used across all operating systems (toss3, toss4 eventually, and toss variants supporting ATS systems) regardless of the ultimate toss3 retirement schedule(s). Such feature updates are part of our ongoing internal deliverables. Removing genders support, which is easily configured out for those who don't need it, is needless code churn and more importantly will generate needless ongoing admin overheads for toss3 systems at this time.

When we have complete solutions to maestro issues 15, 50, and especially 74 would be the appropriate time to review removing genders support. Until then I suggest we close this issue.

**Comment by tom95858** [comment]
@baallan, @morrone, @oceandlr, @valleydlr - I would like to get the genders stuff out of tree in 4.4.1. The deadline is in about a week. Can we please make this happen.

**Comment by baallan** [comment]
> @baallan, @morrone, @oceandlr, @valleydlr - I would like to get the genders stuff out of tree in 4.4.1. The deadline is in about a week. Can we please make this happen.

@tom95858 I suggest we take the rest of this discussion off-line.

**Comment by valleydlr** [comment]
@tom95858 @morrone @baallan @oceandlr I agree that retiring the genders configuration method has been planned for a long time and would also like to see it gone in 4.4.1. I agree with Chris that if Sandia wants to maintain this functionality it should be done as part of local config management. If this patch has been tested and removes all genders dependencies then I am in favor of its acceptance after resolving conflicts.

**Comment by tom95858** [comment]
@morrone, can you make this as ready? Currently it is a draft request.

**Comment by morrone** [comment]
OK, done. Just be aware that landing this means that either Sandia change's their configuration practices on TOSS3 systems one way or the other, or TOSS3 will need to freeze at pre-4.4.1.

**Comment by baallan** [comment]
My understanding from the ug meeting is that this will be landing on 4.5 and not affect 4.4.x/toss3 prior to 4.5.

**Pull request merged**
