### PR TITLE
Fix print formats in ibmad_sampler & ibmad_record_sampler plugins

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
The flag `-Werror -Wall` caught this after I applied PR #1250 .

**Comment by tom95858** [comment]
@nichamon, these changes need to be made in top of tree too, correct? Or did Narate already fix those?

**Comment by tom95858** [comment]
@nichamon, I'll make the change in OVIS-4.4.1 then.

**Comment by nichamon** [comment]
> @nichamon, I'll make the change in OVIS-4.4.1 then.

I just created a pull request #1253 for 4.4.1-rc.

**Comment by nichamon** [comment]
> @nichamon, I have already done this in a staging branch for 4.4.1-RC2. There can be no pull requests on 4.4.1-RC because it contains a couple of changes that resulted in extensive build breakage with -Wall -Werror. 4.4.1-RC2 is a rebase on 4.3.11 minus these changes plus some other fixes. I will push this shortly.

Got it! I'll run the ldms-test suite against 4.4.1-rc2 after you push the changes.

**Comment by morrone** [comment]
Seems fine. But if we are comfortable with C99 stuff, maybe we should include <inttypes.h> and use the PRIx64 macro for this?

**Comment by nichamon** [comment]
A similar fix in #1256 was merged.

**Pull request closed without merging**
