### PR TITLE
Add a thermal sampler that monitors coretemp

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
@tom95858 I didn't see the pull request so I created it from your branch.

**Comment by tom95858** [comment]
@nichmon, I've modified this to use a list of records for each core. I'll update the branch shortly. One issue is that ldms_ls does not report the metric units in the output. It also formats the list data as JSON. Not sure if that's what we want.

**Comment by nichmon** [comment]
Wrong nichmon!

**Comment by nichamon** [comment]
The pull request was replaced by #931.

**Pull request closed without merging**
