### PR TITLE
suppress rollover of empty csv files

### PR DESCRIPTION
**Pull request by baallan**
rolling empty files periodically is an inode-wasting thing to do.
this stops it for store_csv, store_function_csv and the stream csv store.

### CODE REVIEW

**Comment by oceandlr** [comment]
are they timestamped in the names? It is helpful to have date aligned files, even if they are empty

ag

________________________________________
From: Benjamin Allan ***@***.***>
Sent: Monday, August 8, 2022 5:23 PM
To: ovis-hpc/ovis
Cc: Subscribed
Subject: [EXTERNAL] [ovis-hpc/ovis] suppress rollover of empty csv files (PR #998)

rolling empty files periodically is an inode-wasting thing to do.
this stops it for store_csv, store_function_csv and the stream csv store.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ovis-hpc/ovis/pull/998<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0V7NTQCulSOOvOEQnafeUvUDwSwJrk5b%2BDbTeZvDK%2BI%3D&reserved=0>

Commit Summary

  *   ecba4a1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998%2Fcommits%2Fecba4a10dc24b49636ab1b4cc42bc49bb0123d6e&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nxlAzXs%2Bu51FhSWaBvDW%2BKy095r1saAaseGAZZFhigQ%3D&reserved=0> suppress rollover of empty csv files

File Changes

(6 files<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998%2Ffiles&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rJFfockVw0rflYH761SDOAXPPePTw9ZK5fNLmrGL71A%3D&reserved=0>)

  *   M ldms/man/Plugin_store_csv.man<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998%2Ffiles%23diff-b47f991106a60d6a28eadd919f99506c57795c7cefa0c4dddeb9c5d7b5a1fa5c&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pUTH20%2BXEQBkPitSjIF4SlOED9VLIYe5JAKMhKPXRSQ%3D&reserved=0> (3)
  *   M ldms/man/Plugin_store_function_csv.man<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998%2Ffiles%23diff-bd9b66c5195ece8e60f456413c1dc49eb42676664e3712352381b553bbaee010&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dyAvNrNRfXQ9VPZ1r0zWJwKscmGr3T1GH%2F2%2FU%2BYsb5U%3D&reserved=0> (2)
  *   M ldms/src/store/store_csv.c<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998%2Ffiles%23diff-6faddffb8ac1bec776029d5b042e770561b25d68b8c30556e47237e57120cd0a&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X8FIbH4hJRndfg%2BzusNNWDiG8VSpOxNvP2tYp35F2Gw%3D&reserved=0> (3)
  *   M ldms/src/store/store_function_csv.c<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998%2Ffiles%23diff-1194e68067365d651d583962cf5f2e354b7f9f2aff81eea9612398a284e69a7b&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FR7o%2FxZq1qngxSMdb2kjhcGVYkaZudFhT46xfxszdzM%3D&reserved=0> (6)
  *   M ldms/src/store/stream/Plugin_stream_csv_store.man<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998%2Ffiles%23diff-9c43716f636475b5ffdb91f0f1a735c39f43c3ef01254bc84c2e62ced823c084&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Tg%2BR3OPXm0UabwkORubdX4mwdRlm4nSoEh5aK1D0ZDs%3D&reserved=0> (3)
  *   M ldms/src/store/stream/stream_csv_store.c<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998%2Ffiles%23diff-cb6cd86acabc2f8b5d20aa0f5aeb4a9a5658809c954b7e4e476393b37be42610&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kP3VCASM80F9bDgpjFqP7OFOTaJGtYIKogFURmkMPeU%3D&reserved=0> (2)

Patch Links:

  *   https://github.com/ovis-hpc/ovis/pull/998.patch<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998.patch&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1u9Tw%2FVRKwI8wggJxHVu7pQ989a0IqeiN6EEP8eudKU%3D&reserved=0>
  *   https://github.com/ovis-hpc/ovis/pull/998.diff<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fovis-hpc%2Fovis%2Fpull%2F998.diff&data=05%7C01%7Cgentile%40sandia.gov%7C29f89234befb40d50d6208da7995046a%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637955978175534974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D24eZNYa8pb5YqJkYdfdTtWksjUzbs2jEuPeUjnKd0k%3D&reserved=0>

**Comment by baallan** [comment]
@oceandlr the usual timestamping applies.  WRT alignment, the usual cases in which this patch will be active (L2 network blockage or monitored cluster is down) will preserve the alignment of file names.  The only 'expected' case where the alignment would be disjoint is that of event-driven data being absent (no app publishing) while sampler data continues.

**Comment by oceandlr** [comment]
Sorry __- im not understanding this. A more detailed example would help.
In general, I am against not having all the timestamped files, even if they are empty. Often we would pull out files in date ranges and that made it easy to tell if there was missing data and what samplers were supposed to be active.

What is the case that is driving this change?

Thanks
ag

________________________________________
From: Benjamin Allan ***@***.***>
Sent: Tuesday, August 9, 2022 9:16 AM
To: ovis-hpc/ovis
Cc: Gentile, Ann; Mention
Subject: [EXTERNAL] Re: [ovis-hpc/ovis] suppress rollover of empty csv files (PR #998)

@oceandlr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foceandlr&data=05%7C01%7Cgentile%40sandia.gov%7C0a8816ee93424eff222608da7a1a1b2e%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637956549806212115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G5npwsPDUexcqc01172PerrbXsHmfsSQn497bt7Jmmw%3D&reserved=0> the usual timestamping applies. WRT alignment, the usual cases in which this patch will be active (L2 network blockage or monitored cluster is down) will preserve the alignment of file names. The only 'expected' case where the alignment would be disjoint is that of event-driven data being absent (no app publishing) while sampler data continues.

**Comment by baallan** [comment]
I can modify the patch so that a default-off option enables the new behavior. Would that be satisfactory?

A very simplified explanation of the driving cases is that at high rollover frequencies (such as used for low-latency ingest pipelines), thousands of empty files is undesirable.

**Comment by tom95858** [comment]
Regardless of what @baallan and @oceandlr decide, I think any change should require significant testing with test cases and test results posted here to be accepted.

**Comment by baallan** [comment]
marking as draft until done converting patch so that the old behavior remains the default and the test scripts are included.

**Comment by tom95858** [comment]
I guess I'm not getting the motivation for this change. Without this change you know which dates are missing data, with it, you need to infer the missing data from the missing file names. What is the symptom that this is addressing. Are you experiencing inode exhaustion; or is this speculation?

**Comment by baallan** [comment]
@tom95858 With this change, you still see the empty rollover files by default and we can suppress them in if we want to. Yes, we have experienced massive undesired, unnecessary inode consumption in abnormal situations over weekends/holidays when using high rollover frequencies (e.g. every 5 minute) for low latency ingest to things other than sosdb. 

Absence of files is as meaningful in most situations as a long list of size 0 files; we have systemd logs of when daemons go up and down.

**Comment by tom95858** [comment]
Ok, so this is a test thing primarily. Obviously rollover schedules of 5 minutes is not the norm.

**Comment by tom95858** [comment]
@oceandlr, are you OK with this change? If so, I will happily merge.

**Comment by oceandlr** [comment]
I haven't looked at the implementation, so I cannot say about that, but it should be straightforward.

I think the concept would not hurt anything, however, *in general* it is worth considering how we evaluate which options we add. We have heard from people that too many options are difficult to track and add technical debt.

ag

________________________________________
From: Tom Tucker ***@***.***>
Sent: Thursday, September 1, 2022 2:47 PM
To: ovis-hpc/ovis
Cc: Gentile, Ann; Mention
Subject: [EXTERNAL] Re: [ovis-hpc/ovis] suppress rollover of empty csv files (PR #998)

@oceandlr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foceandlr&data=05%7C01%7Cgentile%40sandia.gov%7Cf7fb46d7471c488c2d7008da8c5b2684%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637976620358483191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yL4HQwRSZAP8dSJKyKygp46wKzrxw0MNtA01WuOVPI0%3D&reserved=0>, are you OK with this change? If so, I will happily merge.

**Pull request merged**
