### PR TITLE
LDMS rail + stream

### PR DESCRIPTION
**Pull request by narategithub**
A work-in-progress on LDMS transport rails and LDMS streams (replacing `ldmsd_stream`)

Tests associated with this PR:
- [ldms-test/ldms_rail_test](https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldms_rail_test)
- [ldms-test/ldms_stream_test](https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldms_stream_test)
- [ldms-test/ldmsd_stream_test2](https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldmsd_stream_test2) # <-- temporary placeholder; it will replace ldmsd_stream_test

### CODE REVIEW

**Comment by narategithub** [comment]
@tom95858 I took `origin/ldms-rail-stream-wip-for-narate` and rebased it on top of current `OVIS-4` (7b372c6c1). This (95fd59e67) has been tested with [`agg_slurm_test`](https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldmsd_stream_test2), [`ldms_rail_test`](https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldms_rail_test), [`ldms_stream_test`](https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldms_rail_test), and [`ldmsd_stream_test2`](https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldmsd_stream_test2).

**Comment by nichamon** [comment]
@narategithub Are you still working on this? It is a draft pull request. I want my patch that refactors LDMSD with pre-defined log infrastructures in V4.4. Yours and mine will cause many conflicts, as happened in ldms and zap. I think it's easier to rebase mine on the rail change.

Should I try to rebase my branch on top of this now? Or should I wait until this pull request is merged?

**Comment by narategithub** [comment]
> @narategithub Are you still working on this? It is a draft pull request. I want my patch that refactors LDMSD with pre-defined log infrastructures in V4.4. Yours and mine will cause many conflicts, as happened in ldms and zap. I think it's easier to rebase mine on the rail change.
> 
> Should I try to rebase my branch on top of this now? Or should I wait until this pull request is merged?

Tom (@tom95858) is reviewing this. But, I think you can work on top of this.

**Comment by nichamon** [comment]
> Tom (@tom95858) is reviewing this. But, I think you can work on top of this.

I tried rebasing my ldmsd with ovis_log change on top of this. There was only one conflict, and it was trivial to fix.

**Comment by tom95858** [comment]
Narate did u take my merge changes?

**Comment by narategithub** [comment]
> Narate did u take my merge changes?

Yes I did. But since your changes (`rail-stream-wip-for-narate`) were behind `OVIS-4`, I rebased that on top of current OVIS-4 (7b372c6c1) and verify it with the test cases above.

**Comment by narategithub** [comment]
@tom95858 This has just been rebased on top of 564784aa (top of OVIS-4 as of June 28). It also passed the following related stream tests:
- https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldms_stream_test
- https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldmsd_stream_test2
- https://github.com/narategithub/ldms-test/blob/rail-stream-wip/slurm_stream_test
- https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldmsd_rail_test
- https://github.com/narategithub/ldms-test/blob/rail-stream-wip/ldms_rail_test

**Pull request merged**
