### PR TITLE
add omnipath network decomp for ldms-ibnet-sampler-gen

### PR DESCRIPTION
**Pull request by baallan**

### CODE REVIEW

**Comment by tom95858** [comment]
@baallan, this says WIP, but do you want it merged?

**Comment by baallan** [comment]
@tom95858 not just yet.

**Comment by baallan** [comment]
@tom95858 please merge this one. @morrone I can't find a button to provoke the actions bits to check this PR that was created before they were instituted.

**Comment by morrone** [comment]
@baallan , yes, I am not aware of any way to manually trigger the actions. The action in the .github/workflows/test-make-dist.yaml is triggered on a push to the OVIS-4 branch, or a pull request for the OVIS-4 branch.

If you want to trigger a test build, you could probably edit your existing commit, and then force-push your v4_ibnet_sampler_omnipath branch again. But that probably isn't necessary to force things for the PRs that existed before the workflow. The tests will happen when the changes are merged, so the test will still get run in the end, and we'll know if make dist goes catastrophically wrong.

**Pull request merged**
